-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    sha: v0.52.0
    hooks:
    -   id: scss-lint
