-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 6b1aa19425b35f8c34f43ada8f1045b028dc19a5
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    sha: 7265d327b943b0e740761f706bd2f1645f948908
    hooks:
    -   id: scss-lint
