-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 64943e86417774b9d6ba63c74e00f8cc3e2119e0
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: requirements-txt-fixer
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    sha: f840ac610d8d9d76b666062416241f2156b3f388
    hooks:
    -   id: scss-lint
